"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TodoIcon = exports.CheckIcon = exports.RemoveIcon = exports.EditIcon = exports.LightModeIcon = exports.DarkModeIcon = exports.TableIcon = exports.ListIcon = void 0;
const icons_material_1 = require("@mui/icons-material");
exports.ListIcon = icons_material_1.FormatListBulleted;
exports.TableIcon = icons_material_1.GridOn;
exports.DarkModeIcon = icons_material_1.DarkMode;
exports.LightModeIcon = icons_material_1.LightMode;
exports.EditIcon = icons_material_1.Edit;
exports.RemoveIcon = icons_material_1.Remove;
exports.CheckIcon = icons_material_1.Check;
exports.TodoIcon = icons_material_1.TaskAlt;
